---
- name: Adjust resources and configuration
  block:
    - name: Display resource adjustment information
      ansible.builtin.debug:
        msg: |
          ⚙️ Adjusting Resources
          =====================
          Environment: {{ dest_env }}
          Customer Alias: {{ customer }}
          Dry Run: {{ dry_run_mode | default(false) }}

    - name: Check if adjust resources script exists (adjust_db.ps1)
      ansible.builtin.stat:
        path: "{{ role_path }}/files/3_adjust_resources/adjust_db.ps1"
      register: adjust_resources_main_script

    - name: Check if adjust resources directory exists
      ansible.builtin.stat:
        path: "{{ role_path }}/files/3_adjust_resources"
      register: adjust_resources_dir

    - name: Execute adjust resources script (adjust_db.ps1)
      ansible.builtin.command: >
        pwsh -File {{ role_path }}/files/3_adjust_resources/adjust_db.ps1
        -domain "{{ domain | default('dev.azure') }}"
        -CustomerAlias "{{ customer }}"
        -destination "{{ dest_env }}"
        -DestinationNamespace "{{ dest_ns }}"
        {{ '-DryRun' if dry_run else '' }}
      register: adjust_resources_result
      changed_when: not dry_run
      when: adjust_resources_main_script.stat.exists
      failed_when: false

    - name: Display adjust resources result
      ansible.builtin.debug:
        msg: |
          ⚡ Adjust Resources Script Results:
          Exit Code: {{ adjust_resources_result.rc | default('N/A') }}
          Command: pwsh -File {{ role_path }}/files/3_adjust_resources/AdjustResources.ps1 -environment "{{ dest_env }}" -namespace "{{ dest_ns }}" -customerAlias "{{ customer }}" {{ '-DryRun' if dry_run else '' }}
          
          📤 STDOUT:
          {{ adjust_resources_result.stdout | default('(no output)') }}
          
          📤 STDERR:
          {{ adjust_resources_result.stderr | default('(no errors)') }}
      when: adjust_resources_result is defined

    - name: Fail if adjust resources had critical error
      ansible.builtin.fail:
        msg: "Adjust resources script failed with exit code {{ adjust_resources_result.rc }}"
      when: 
        - adjust_resources_result is defined
        - adjust_resources_result.rc is defined
        - adjust_resources_result.rc != 0
        - not (dry_run | default(false))

    - name: Use existing alignment roles as fallback
      block:
        - name: Adjust terraform configuration
          ansible.builtin.include_role:
            name: align-terraform-configuration
          vars:
            align_dest_subscription_id: "{{ dest_subscription_id }}"
            align_dest_region_alias: "{{ dest_env }}"
            align_terraform_env_path: "{{ terraform_env_path | default('public') }}"

        - name: Adjust runtime configuration
          ansible.builtin.include_role:
            name: align-runtime-configuration
          vars:
            align_source_subscription_id: "{{ source_subscription_id }}"
            align_dest_subscription_id: "{{ dest_subscription_id }}"
            align_dest_resource_group: "{{ dest_rg | default('rg-mnfro-intd-' + dest_env + '-weu') }}"
            align_source_region_alias: "{{ source_env }}"
            align_dest_region_alias: "{{ dest_env }}"
            align_dest_customer_alias: "{{ customer }}"
            align_terraform_env_path: "{{ terraform_env_path | default('public') }}"
      when: not adjust_resources_main_script.stat.exists and not dry_run

    - name: Display missing script information
      ansible.builtin.debug:
        msg: |
          ℹ️ Adjust Resources Main Script Not Found
          ========================================
          Expected: {{ role_path }}/files/3_adjust_resources/AdjustResources.ps1
          Using fallback Ansible roles instead.
          Available scripts in directory:
          {{ ansible_facts.gather_subset | default([]) }}
      when: not adjust_resources_main_script.stat.exists

    - name: Display adjust resources result
      ansible.builtin.debug:
        var: adjust_resources_result.stdout_lines
      when: adjust_resources_result.stdout_lines is defined
