---
- name: Copy database from source to destination
  block:
    - name: Display database copy information
      ansible.builtin.debug:
        msg: |
          📋 Copying Database
          ==================
          Source: {{ source_env }} ({{ source_ns }})
          Destination: {{ dest_env }} ({{ dest_ns }})
          Dry Run: {{ dry_run_mode | default(false) }}

    - name: Check if PowerShell is available
      ansible.builtin.command: which pwsh
      register: pwsh_check
      failed_when: false
      changed_when: false

    - name: Execute database copy script (if PowerShell available)
      ansible.builtin.command: >
        pwsh -File {{ role_path }}/files/2_copy_database/copy_database.ps1
        -source "{{ source_env }}"
        -destination "{{ dest_env }}"
        -SourceNamespace "{{ source_ns }}"
        -DestinationNamespace "{{ dest_ns }}"
        {{ '-DryRun' if (dry_run_mode | default(false)) else '' }}
      register: copy_db_result
      changed_when: not (dry_run_mode | default(false))
      when: pwsh_check.rc == 0
      failed_when: false

    - name: Display PowerShell not available warning
      ansible.builtin.debug:
        msg: |
          ⚠️ PowerShell not available - skipping database copy script
          This is expected in environments without PowerShell Core installed.
          In production (Semaphore), ensure PowerShell Core is available.
      when: pwsh_check.rc != 0

    - name: Display database copy result
      ansible.builtin.debug:
        var: copy_db_result.stdout_lines
      when: copy_db_result.stdout_lines is defined
