---
- name: Full Self-Service Refresh Workflow (11 Steps)
  block:
    - name: Step 1 - Create restore point in time
      ansible.builtin.include_tasks: restore_point.yaml
      when: skip_restore is not defined or not skip_restore

    - name: Step 2 - Stop destination environment
      ansible.builtin.include_tasks: stop_environment.yaml
      when: skip_stop is not defined or not skip_stop

    - name: Step 3 - Copy attachments
      ansible.builtin.include_tasks: copy_attachments.yaml
      when: skip_copy_attachments is not defined or not skip_copy_attachments

    - name: Step 4 - Copy database
      ansible.builtin.include_tasks: copy_database.yaml
      when: skip_copy_database is not defined or not skip_copy_database

    - name: Step 5 - Cleanup environment configuration
      ansible.builtin.include_tasks: cleanup_environment_config.yaml
      when: skip_cleanup_config is not defined or not skip_cleanup_config

    - name: Step 6 - Revert SQL users
      ansible.builtin.include_tasks: revert_sql_users.yaml
      when: skip_revert_users is not defined or not skip_revert_users

    - name: Step 7 - Adjust resources
      ansible.builtin.include_tasks: adjust_resources.yaml
      when: skip_adjust_resources is not defined or not skip_adjust_resources

    - name: Step 8 - Delete replicas
      ansible.builtin.include_tasks: delete_replicas.yaml
      when: skip_delete_replicas is not defined or not skip_delete_replicas

    - name: Step 9 - Configure users
      ansible.builtin.include_tasks: configure_users.yaml
      when: skip_configure_users is not defined or not skip_configure_users

    - name: Step 10 - Start environment
      ansible.builtin.include_tasks: start_environment.yaml
      when: skip_start is not defined or not skip_start

    - name: Step 11 - Cleanup restored databases
      ansible.builtin.include_tasks: cleanup_restored_dbs.yaml
      when: skip_cleanup is not defined or not skip_cleanup

    - name: Refresh completed successfully
      ansible.builtin.debug:
        msg: |
          ✅ Self-Service Data Refresh Completed Successfully (11 Steps)
          =============================================================
          Source: {{ source_environment }} → Destination: {{ dest_environment }}
          Duration: {{ ansible_date_time.epoch | int - (start_time | default(ansible_date_time.epoch)) | int }} seconds
