---
- name: Manage permissions and access
  block:
    - name: Display permission management information
      ansible.builtin.debug:
        msg: |
          🔐 Managing Permissions
          =======================
          Environment: {{ dest_env }}
          Customer Alias: {{ customer }}
          Dry Run: {{ dry_run_mode | default(false) }}

    - name: Check if manage permissions main script exists
      ansible.builtin.stat:
        path: "{{ role_path }}/files/8_manage_permissions/ManagePermissions.ps1"
      register: manage_permissions_main_script

    - name: Check if manage permissions directory exists
      ansible.builtin.stat:
        path: "{{ role_path }}/files/8_manage_permissions"
      register: manage_permissions_dir

    - name: Execute manage permissions script
      ansible.builtin.command: >
        pwsh -File {{ role_path }}/files/8_manage_permissions/ManagePermissions.ps1
        -environment "{{ dest_env }}"
        -namespace "{{ dest_ns }}"
        -customerAlias "{{ customer }}"
        {{ '-DryRun' if dry_run else '' }}
      register: manage_permissions_result
      changed_when: not dry_run
      when: manage_permissions_main_script.stat.exists
      failed_when: false

    - name: Enable health alerts as fallback
      ansible.builtin.include_role:
        name: azure_monitor
      vars:
        alert_action: "enable"
        alert_region_alias: "{{ dest_env }}"
        alert_resource_group: "{{ dest_rg | default('rg-mnfro-intd-' + dest_env + '-weu') }}"
        alert_subscription_id: "{{ dest_subscription_id }}"
        alert_hub_resource_group: "{{ hub_resource_group | default('rg-mnfro-hub-weu') }}"
        alert_hub_subscription_id: "{{ hub_subscription_id | default('a9261cc1-d170-491d-b8fa-23ef0ad88ba3') }}"
      when: not manage_permissions_main_script.stat.exists and not dry_run

    - name: Display missing script information
      ansible.builtin.debug:
        msg: |
          ℹ️ Manage Permissions Main Script Not Found
          ==========================================
          Expected: {{ role_path }}/files/8_manage_permissions/ManagePermissions.ps1
          Using fallback Ansible roles instead.
      when: not manage_permissions_main_script.stat.exists

    - name: Display manage permissions result
      ansible.builtin.debug:
        var: manage_permissions_result.stdout_lines
      when: manage_permissions_result.stdout_lines is defined
