---
- name: Create restore point in time
  block:
    - name: Set start time
      ansible.builtin.set_fact:
        start_time: "{{ ansible_date_time.epoch }}"

    - name: Set default restore datetime and timezone
      ansible.builtin.set_fact:
        restore_datetime: "{{ restore_datetime | default('') }}"
        timezone: "{{ timezone | default(ansible_date_time.tz) }}"

    - name: Display restore point information
      ansible.builtin.debug:
        msg: |
          🕒 Creating Restore Point
          ========================
          Source Environment: {{ source_env }} ({{ source_ns }})
          Restore DateTime: {{ restore_datetime }}
          Timezone: {{ timezone }}
          Dry Run: {{ dry_run_mode | default(false) }}

    - name: Check if PowerShell is available
      ansible.builtin.command: which pwsh
      register: pwsh_check
      failed_when: false
      changed_when: false

    - name: Check if PowerShell Core is available
      ansible.builtin.command: which powershell
      register: powershell_check
      failed_when: false
      changed_when: false
      when: pwsh_check.rc != 0

    - name: Execute restore point script (if PowerShell available)
      ansible.builtin.command: >
        pwsh -File {{ role_path }}/files/0_restore_point_in_time/RestorePointInTime.ps1
        -source "{{ source_env }}"
        -SourceNamespace "{{ source_ns }}"
        -MaxWaitMinutes {{ max_wait | default(30) }}
        {{ '-DryRun' if (dry_run_mode | default(false)) else '' }}
      register: restore_result
      changed_when: not (dry_run_mode | default(false))
      when: pwsh_check.rc == 0 or powershell_check.rc == 0
      failed_when: false

    - name: Display PowerShell not available warning
      ansible.builtin.debug:
        msg: |
          ⚠️ PowerShell not available - skipping restore point script
          This is expected in environments without PowerShell Core installed.
          In production (Semaphore), ensure PowerShell Core is available.
      when: pwsh_check.rc != 0 and (powershell_check is not defined or powershell_check.rc != 0)

    - name: Display restore point result
      ansible.builtin.debug:
        var: restore_result.stdout_lines
      when: restore_result.stdout_lines is defined
