---
# tasks/main.yml
- name: Copy alert management script
  copy:
    src: manage_alert.sh
    dest: /tmp/manage_alert.sh
    mode: '0755'

- name: Manage Azure Monitor alert
  command: >
    /tmp/manage_alert.sh
    --action="{{ alert_action }}"
    --region-alias="{{ alert_region_alias }}"
    --dest-resource-group="{{ alert_resource_group }}"
    --hub-resource-group="{{ alert_hub_resource_group }}"
    --dest-subscription-id="{{ alert_subscription_id }}"
    --hub-subscription-id="{{ alert_hub_subscription_id }}"
    --cloud="{{ cloud_environment }}"
    {% if ansible_check_mode %}--dry-run{% endif %}
