---
# tasks/main.yml
- name: Copy adjust_db script to /tmp
  ansible.builtin.copy:
    src: files/adjust_db.ps1
    dest: /tmp/adjust_db.ps1
    mode: '0755'

- name: Copy adjust_sql_aad_users script to /tmp
  ansible.builtin.copy:
    src: files/adjust_sql_aad_users.ps1
    dest: /tmp/adjust_sql_aad_users.ps1
    mode: '0755'

- name: Copy sysadmin_passwords script to /tmp
  ansible.builtin.copy:
    src: files/sysadmin_passwords.sh
    dest: /tmp/sysadmin_passwords.sh
    mode: '0755'

- name: 001 Realigning destination database
  ansible.builtin.command: >
    pwsh /tmp/adjust_sql_aad_users.ps1
    -Cloud {{ cloud_environment }}
    -DestinationSubscriptionId {{ align_dest_subscription_id }}
    -DestinationResourceGroup {{ align_dest_resource_group }}
    -SourceSubscriptionId {{ align_source_subscription_id }}

- name: 002 Realigning destination database
  ansible.builtin.command: >
    pwsh /tmp/adjust_db.ps1
    -Cloud {{ cloud_environment }}
    -DestinationSubscriptionId {{ align_dest_subscription_id }}
    -DestinationResourceGroup {{ align_dest_resource_group }}
    -DestinationCustomerAlias {{ align_dest_customer_alias }}
    -DestinationRegionAlias {{ align_dest_region_alias }}

# - name: 003 Rerun baselines
#   ansible.builtin.command: >
#     Connect-AzAccount -Environment {{ cloud_environment }}
#     pwsh /terraform/apps/modules/database/scripts/sql_database_config.ps1
#     -Environments {{ align_dest_region_alias }}
# #    --cloud="{{ cloud_environment }}"

# - name: 004 Align sysadmin password
#   ansible.builtin.command: >
#     /tmp/sysadmin_passwords.sh
