---
- name: Self-Service Data Refresh
  hosts: localhost
  environment:
    AZURE_CONFIG_DIR: /home/semaphore/.azure
  vars:
    # === Required Variables ===
    # These must be defined when running the playbook
    
    # === REQUIRED PARAMETERS - No defaults, must be provided ===
    source_environment: "{{ source_env }}"
    source_subscription_id: "{{ source_sub_id }}"
    source_resource_group: "{{ source_rg | default('rg-mnfro-intd-' + source_env + '-weu') }}"
    
    dest_environment: "{{ dest_env }}"
    dest_subscription_id: "{{ dest_sub_id }}"
    dest_resource_group: "{{ dest_rg | default('rg-mnfro-intd-' + dest_env + '-weu') }}"
    dest_cluster_name: "{{ dest_cluster | default('aks-mnfro-intd-' + dest_env + '-weu') }}"
    
    # === REQUIRED NAMESPACE PARAMETERS ===
    # These are set in the role's set_fact task to avoid circular references
    
    # === OPTIONAL PARAMETERS WITH DEFAULTS ===
    # These are now set in the role to avoid circular references
    terraform_env_path: "{{ terraform_path | default('public') }}"
    
    # Hub configuration for monitoring
    hub_resource_group: "{{ hub_rg | default('rg-mnfro-hub-weu') }}"
    hub_subscription_id: "{{ hub_sub_id | default('a9261cc1-d170-491d-b8fa-23ef0ad88ba3') }}"
    
    # === OPERATION CONFIGURATION ===
    dry_run: "{{ dry_run_mode | default(false) | bool }}"
    max_wait_minutes: "{{ max_wait | default(30) | int }}"
    operation: "{{ op | default('full') }}"
    
    # === Step Control Variables ===
    # Set to true to skip specific steps
    skip_restore: "{{ skip_restore_step | default(false) | bool }}"
    skip_stop: "{{ skip_stop_step | default(false) | bool }}"
    skip_copy_attachments: "{{ skip_copy_attachments_step | default(false) | bool }}"
    skip_copy_database: "{{ skip_copy_database_step | default(false) | bool }}"
    skip_adjust_resources: "{{ skip_adjust_resources_step | default(false) | bool }}"
    skip_start: "{{ skip_start_step | default(false) | bool }}"
    skip_cleanup: "{{ skip_cleanup_step | default(false) | bool }}"
    skip_permissions: "{{ skip_permissions_step | default(false) | bool }}"

  pre_tasks:
    - name: Validate required parameters
      ansible.builtin.assert:
        that:
          - source_env is defined
          - dest_env is defined
          - source_sub_id is defined
          - dest_sub_id is defined
          - source_ns is defined
          - dest_ns is defined
          - customer is defined
        fail_msg: |
          ❌ Missing required parameters!
          
          Required parameters:
          • source_env (source environment name)
          • dest_env (destination environment name) 
          • source_sub_id (source subscription ID)
          • dest_sub_id (destination subscription ID)
          • source_ns (source namespace)
          • dest_ns (destination namespace)
          • customer (customer alias)
          
          Example usage:
          ansible-playbook playbooks/self_service_refresh.yaml \
            --extra-vars "source_env=gov002 dest_env=gov001 \
                         source_sub_id=xxx dest_sub_id=yyy \
                         source_ns=manufacturo dest_ns=test \
                         customer=gov001-test"

    - name: Display playbook information
      ansible.builtin.debug:
        msg: |
          🚀 Self-Service Data Refresh Playbook
          ====================================
          
          📊 Environment Configuration:
          • Source: {{ source_environment }} ({{ source_ns }})
          • Destination: {{ dest_environment }} ({{ dest_ns }})
          • Cloud: {{ cloud | default('AzureUSGovernment') }}
          • Customer: {{ customer }}
          
          ⚙️ Operation Settings:
          • Operation: {{ operation }}
          • Dry Run: {{ dry_run }}
          • Max Wait: {{ max_wait_minutes }} minutes
          
          🎯 Step Control:
          • Skip Restore: {{ skip_restore }}
          • Skip Stop Environment: {{ skip_stop }}
          • Skip Copy Attachments: {{ skip_copy_attachments }}
          • Skip Copy Database: {{ skip_copy_database }}
          • Skip Adjust Resources: {{ skip_adjust_resources }}
          • Skip Start Environment: {{ skip_start }}
          • Skip Cleanup: {{ skip_cleanup }}
          • Skip Permissions: {{ skip_permissions }}

    - name: Confirm operation in production
      ansible.builtin.pause:
        prompt: |
          ⚠️  WARNING: You are about to perform a data refresh operation!
          
          This will:
          1. Create a restore point from {{ source_environment }}
          2. Stop the {{ dest_environment }} environment
          3. Copy data from {{ source_environment }} to {{ dest_environment }}
          4. Reconfigure and restart {{ dest_environment }}
          
          Type 'yes' to continue, or 'no' to abort
      register: confirm_operation
      when: not dry_run and dest_environment in ['prod', 'production']

    - name: Abort if not confirmed
      ansible.builtin.fail:
        msg: "Operation aborted by user"
      when: 
        - not dry_run 
        - dest_environment in ['prod', 'production']
        - confirm_operation.user_input | lower != 'yes'

  tasks:
    - name: Execute self-service refresh
      ansible.builtin.include_role:
        name: self_service_refresh
      vars:
        # Pass the input variables directly to avoid circular references
        source_env: "{{ source_env }}"
        dest_env: "{{ dest_env }}"
        source_sub_id: "{{ source_sub_id }}"
        dest_sub_id: "{{ dest_sub_id }}"
        source_ns: "{{ source_ns }}"
        dest_ns: "{{ dest_ns }}"
        customer: "{{ customer }}"
        # Cloud variable will be set by role with default
        dry_run_mode: "{{ dry_run }}"
        max_wait: "{{ max_wait_minutes }}"
        op: "{{ operation }}"

  post_tasks:
    - name: Final status report
      ansible.builtin.debug:
        msg: |
          ✅ Self-Service Data Refresh Completed
          ====================================
          
          📊 Summary:
          • Source: {{ source_environment }} → Destination: {{ dest_environment }}
          • Customer: {{ customer_alias }}
          • Operation: {{ operation }}
          • Dry Run: {{ dry_run }}
          • Duration: {{ ansible_date_time.epoch | int - (start_time | default(ansible_date_time.epoch)) | int }} seconds
          
          🎯 Next Steps:
          • Verify application functionality
          • Check data integrity
          • Monitor system performance
          • Update documentation if needed
