---
# tasks/copy-storage-account-contents.yaml
- name: Copy storage firewall management script
  copy:
    src: manage_sa_firewall.sh
    dest: /tmp/manage_sa_firewall.sh
    mode: '0755'

- name: Copy storage copy script
  copy:
    src: copy_storage_account_contents.sh
    dest: /tmp/copy_storage_account_contents.sh
    mode: '0755'

- name: Open SA security and copy attachments
  block:
    - name: Open security boundary
      ansible.builtin.command: >
        /tmp/manage_sa_firewall.sh
        --action="disable"
        --source-subscription-id="{{ source_storage_subscription_id }}"
        --source-rg="{{ source_storage_rg }}"
        --dest-subscription-id="{{ dest_subscription_id }}"
        --dest-rg="{{ dest_storage_rg }}"
        --cloud="{{ cloud_environment }}"
        {% if ansible_check_mode %}--dry-run{% endif %}
      changed_when: true

    - name: Copy storage account contents
      ansible.builtin.command: >
        /tmp/copy_storage_account_contents.sh
        --source-subscription-id="{{ source_storage_subscription_id }}"
        --dest-subscription-id="{{ dest_subscription_id }}"
        --cloud="{{ cloud_environment }}"
        {% if ansible_check_mode %}--dry-run{% endif %}

  rescue:
    - name: Log failure
      ansible.builtin.debug:
        msg: "🚨 Operation failed after opening security."

  always:
    - name: Close security boundary
      ansible.builtin.command: >
        /tmp/manage_sa_firewall.sh
        --action="enable"
        --source-subscription-id="{{ source_storage_subscription_id }}"
        --source-rg="{{ source_storage_rg }}"
        --dest-subscription-id="{{ dest_subscription_id }}"
        --dest-rg="{{ dest_storage_rg }}"
        --cloud="{{ cloud_environment }}"
        {% if ansible_check_mode %}--dry-run{% endif %}
