---
# tasks/delete-destination-backup.yaml
- name: Copy delete_database.sh script to a temporary location
  ansible.builtin.copy:
    src: delete_database.sh
    dest: "/tmp/delete_database.sh"
    mode: '0755' # Make it executable
  delegate_to: localhost

- name: (Delete Destination Backup) Execute delete_database.sh script
  ansible.builtin.command: >
    /tmp/delete_database.sh
    --action="{{ db_action }}"
    --resource-group="{{ db_resource_group }}"
    --cloud="{{ cloud_environment }}"
    --subscription-id="{{ db_subscription_id }}"
    {% if ansible_check_mode %}--dry-run{% endif %}
  args:
    chdir: /tmp # Run from /tmp
  delegate_to: localhost
  register: result
  failed_when: result.rc != 0
  changed_when: result.rc == 0
  
- name: Display start AKS result
  ansible.builtin.debug:
    var: result.stdout_lines
  when: ansible_verbosity >= 2 # Run when -vv or higher is used
